spec-version: 0.30.0
name: nary-products
author: Matej Nižník, Asad Saeeduddin
maintainer: matten@tuta.io, masaeedu@gmail.com
license: MIT

build-type: Simple

dependencies:
- { name: "base", version: '>=4.14 && <4.15' }
- bifunctors

ghc-options: -Wall
default-extensions:
- GADTs

- StandaloneDeriving
- DeriveFunctor
- DerivingVia
- GeneralizedNewtypeDeriving

- ScopedTypeVariables
- RankNTypes
- QuantifiedConstraints

- TypeApplications
- TypeOperators
- MultiParamTypeClasses

- ConstraintKinds
- DataKinds
- PolyKinds
- KindSignatures
- StandaloneKindSignatures

- UndecidableInstances
- FlexibleInstances
- FlexibleContexts
- DefaultSignatures

- ImportQualifiedPost
- LambdaCase

library:
  source-dirs: lib

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - nary-products
